package com.example.shuip.talk.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHAT_MSG.
 */
public class ChatMsg implements BaseEntity {


    public static final int MSG_TYPE_TEXT=1;
    public static final int MSG_TYPE_IMG=2;
    public static final int MSG_TYPE_VOICE=3;
    public static final int MSG_TYPE_VIDEO=4;


    public static final int SEND=0;
    public static final int RECEVIER=1;

    public static final int STATUS_NOSEND=0;
    public static final int STATUS_SEND_SUCCESS=1;
    public static final int STATUS_SEND_FAIL=2;
    public static final int STATUS_READED=3;
    public static final int STATUS_UNREAD=4;





    private Long id;
    private long memberid;
    private long contactid;
    /** Not-null value. */
    private String chatmsg;
    /** Not-null value. */
    private java.util.Date chattime;
    private int chattype;
    private int isreceive;
    private int status;

    public ChatMsg() {
    }

    public ChatMsg(Long id) {
        this.id = id;
    }

    public ChatMsg(Long id, long memberid, long contactid, String chatmsg, java.util.Date chattime, int chattype, int isreceive, int status) {
        this.id = id;
        this.memberid = memberid;
        this.contactid = contactid;
        this.chatmsg = chatmsg;
        this.chattime = chattime;
        this.chattype = chattype;
        this.isreceive = isreceive;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMemberid() {
        return memberid;
    }

    public void setMemberid(long memberid) {
        this.memberid = memberid;
    }

    public long getContactid() {
        return contactid;
    }

    public void setContactid(long contactid) {
        this.contactid = contactid;
    }

    /** Not-null value. */
    public String getChatmsg() {
        return chatmsg;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChatmsg(String chatmsg) {
        this.chatmsg = chatmsg;
    }

    /** Not-null value. */
    public java.util.Date getChattime() {
        return chattime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setChattime(java.util.Date chattime) {
        this.chattime = chattime;
    }

    public int getChattype() {
        return chattype;
    }

    public void setChattype(int chattype) {
        this.chattype = chattype;
    }

    public int getIsreceive() {
        return isreceive;
    }

    public void setIsreceive(int isreceive) {
        this.isreceive = isreceive;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

}
