package com.example.shuip.talk.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.util.Date;

/**
 * Entity mapped to table CONTACT.
 */
public class Contact implements BaseEntity {

    private Long id;
    private long memberid;
    private long contactid;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String headbig;
    /** Not-null value. */
    private String headmid;
    /** Not-null value. */
    private String headsmall;
    /** Not-null value. */
    private Date registeTime;
    /** Not-null value. */
    private Date createtime;
    /** Not-null value. */
    private String pinyin;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, long memberid, long contactid, String email, String name, String headbig, String headmid, String headsmall, Date registetime, Date createtime, String pinyin) {
        this.id = id;
        this.memberid = memberid;
        this.contactid = contactid;
        this.email = email;
        this.name = name;
        this.headbig = headbig;
        this.headmid = headmid;
        this.headsmall = headsmall;
        this.registeTime = registetime;
        this.createtime = createtime;
        this.pinyin = pinyin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getMemberid() {
        return memberid;
    }

    public void setMemberid(long memberid) {
        this.memberid = memberid;
    }

    public long getContactid() {
        return contactid;
    }

    public void setContactid(long contactid) {
        this.contactid = contactid;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getHeadbig() {
        return headbig;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeadbig(String headbig) {
        this.headbig = headbig;
    }

    /** Not-null value. */
    public String getHeadmid() {
        return headmid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeadmid(String headmid) {
        this.headmid = headmid;
    }

    /** Not-null value. */
    public String getHeadsmall() {
        return headsmall;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeadsmall(String headsmall) {
        this.headsmall = headsmall;
    }


    public Date getRegisteTime() {
        return registeTime;
    }

    public void setRegisteTime(Date registeTime) {
        this.registeTime = registeTime;
    }


    /** Not-null value. */
    public Date getCreatetime() {
        return createtime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /** Not-null value. */
    public String getPinyin() {
        return pinyin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    @Override
    public String toString() {
        return memberid + contactid + email + name +
                headbig + headmid + headsmall +
                registeTime.toString() + createtime.toString() + pinyin + "";
    }
}
